name: Ubuntu 24.04 IfcImportPlugin

on:
  # run nightly at 2:00 am

  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Test suite results are created on Ubuntu 22.04, hence we need to use this for testing
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.SUBMODULE_PAT }}
        submodules: 'true'
    - name: install qt6
      run: sudo apt install libgdal-dev qt6-base-dev qt6-base-dev-tools qt6-declarative-dev qt6-svg-dev libqt6opengl6t64 libqt6positioning6 qt6-positioning-dev libqt6positioningquick6 qml6-module-qtpositioning qml6-module-qt-labs-lottieqt zlib1g-dev
    - name: download highs-lib
      working-directory: externals/HiGHS
      run: ./download-highs_Ubuntu24.04.sh
    - name: link submodule libraries
      working-directory: externals
      run: ./createLinuxSymlinks.sh
    - name: build
      working-directory: build/cmake
      run: ./build.sh release
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IfcImportPlugin_Ubuntu2204
        path: bin/release/*.so
