name: Ubuntu 24.04 IfcImportPlugin

on:
  # run nightly at 2:00 am

  # allow to be triggered on github webpage manually
  workflow_dispatch:
  # run whenever someone pushes data
  # WARNING: this may give excessive build times which need to be paid!
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    # Test suite results are created on Ubuntu 22.04, hence we need to use this for testing
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.SUBMODULE_PAT }}
        submodules: 'true'
        
    - name: install qt6
      run: sudo apt-get update && sudo apt-get install -y qt6-base-dev qt6-base-dev-tools qt6-svg-dev zlib1g-dev libgl-dev
          
    - name: link submodule libraries
      working-directory: externals
      run: ./createLinuxSymlinks.sh
      
    - name: download highs-lib
      working-directory: externals/HiGHS
      run: ./download-highs_Ubuntu24.04.sh
      
    - name: build
      working-directory: build/cmake
      run: ./build.sh release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IfcImportPlugin_Ubuntu2404
        path: bin/release/*.so
